### ISSUE TITLE
Alt + Shift + T not working in linux OS

### ISSUE THREAD

**Issue by vinothwindows47** [RobertWHurst/KeyboardJS#138] opened 2018-04-20 06:40 UTC

**Comment by jean-emmanuel** [comment] 2018-10-10 08:07
Can you elaborate ? What is the expected behavior ?

**Comment by jean-emmanuel** [comment] 2018-10-10 08:08
Haha wrong repository sorry ;)

**Comment by RobertWHurst** [comment] 2020-06-05 01:02
This is likely because the browser or OS is stealing the keypress from the browser, this can happen with modifier keys some times. That said I'll try it out on my Linux VM

**Comment by RobertWHurst** [comment] 2020-06-05 03:29
I couldn't repo this one. Is it still an issue on the latest version? I'm going to close this for now, but please follow up if you can/want to.

**Closed by RobertWHurst** 2020-06-05 03:29 UTC
Labels: Bug, Linux
